pipeline {
    agent any

    stages {
        stage('Checkout & Build') {
            steps {
                // Esto crea una carpeta corta para evitar el límite de 260 caracteres
                ws("C:/jk/${env.JOB_NAME}") {
                    checkout scm
                    bat 'git config core.longpaths true'
                    bat './gradlew build'
                }
            }
        }
    }
}