# ==========================================
# Plataforma OpenShift
# ==========================================
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: openshift
  description: Aplicaciones, servicios y componentes desplegados en la plataforma OpenShift.
  tags:
    - openshift
spec:
  type: system
  owner: group:infrastructure


---
# ==========================================
# Plataforma WebSphere
# ==========================================
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: websphere
  description: Aplicaciones, servicios y componentes desplegados en la plataforma WebSphere.
  tags:
    - websphere
spec:
  owner: group:developers


---
# ==========================================
# Sistema de Ticketing y Pagos
# ==========================================
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: sistema-ticketing
  description: Sistema para la compra de billetes, procesamiento de pagos, fijación de precios y gestión de reservas asociadas.
  tags:
    - ticketing
    - pricing
    - payments
spec:
  owner: group:team-ticketing

---
# ==========================================
# Base de datos PostgreSQL en OpenShift
# ==========================================
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgres
  description: Base de datos PostgreSQL desplegada en OpenShift.
  tags:
    - postgresql
    - database
    - openshift
spec:
  type: database
  owner: group:infrastructure
  system: openshift
  lifecycle: production

---
# ==========================================
# Cola de mensajes AWS SQS para procesamiento de pagos
# ==========================================
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: aws-sqs-payments
  description: Cola SQS utilizada para procesar eventos y transacciones del sistema de ticketing y pagos.
  tags:
    - aws
    - sqs
    - queue
    - messaging
spec:
  type: queue
  owner: group:team-ticketing
  system: sistema-ticketing
  lifecycle: production

---
# ==========================================
# Sistema de Movilidad y Rutas
# ==========================================
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: sistema-movilidad-rutas
  description: Sistema encargado de gestionar rutas, paradas, planificación de viajes y geolocalización de infraestructuras.
  tags:
    - mobility
    - routes
    - geolocation
spec:
  owner: group:team-movilidad


---
# ==========================================
# Sistema de Gestión de Flota
# ==========================================
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: sistema-gestion-flota
  description: Sistema encargado del control de flota, mantenimiento, posición en tiempo real e incidencias asociadas.
  tags:
    - fleet
    - realtime
    - incidents
spec:
  owner: group:team-flota

---
# ==========================================
# Componente de prueba para integración Jenkins
# ==========================================
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prueba102-android
  description: Componente de prueba para validar la integración de Backstage con Jenkins.
  tags:
    - android
    - jenkins
    - ci
    - test
  annotations:
    jenkins.io/job-full-name: backstage/prueba104-android-build
spec:
  type: service
  lifecycle: experimental
  owner: group:developers
  system: openshift
