---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: davyyelor
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: davidelorzag
  annotations:
    graph.microsoft.com/user-id: 37614d18-4ac0-4fbd-a96c-f773a8778c5c
spec:
  profile:
    displayName: David Elorza
    email: davidelorzag@gmail.com
  memberOf:
    - guests