pipeline {
  agent any

  tools {
    jdk 'temurin-17'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build') {
      steps {
        sh './gradlew build'
      }
    }
  }
}
